/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ScoreEntry = IDL.Record({
  'score' : IDL.Nat,
  'tables' : IDL.Vec(IDL.Nat),
  'timestamp' : IDL.Int,
  'playerName' : IDL.Text,
  'questions' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getLeaderboard' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
  'getScoresByPlayer' : IDL.Func([IDL.Text], [IDL.Vec(ScoreEntry)], ['query']),
  'getTotalGames' : IDL.Func([], [IDL.Nat], ['query']),
  'saveScore' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Nat)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ScoreEntry = IDL.Record({
    'score' : IDL.Nat,
    'tables' : IDL.Vec(IDL.Nat),
    'timestamp' : IDL.Int,
    'playerName' : IDL.Text,
    'questions' : IDL.Nat,
  });
  
  return IDL.Service({
    'getLeaderboard' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
    'getScoresByPlayer' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ScoreEntry)],
        ['query'],
      ),
    'getTotalGames' : IDL.Func([], [IDL.Nat], ['query']),
    'saveScore' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Nat)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };